"""Modlist Merger tool — merge two MO2 profile directories."""

from __future__ import annotations

import logging
import os
from pathlib import Path

from imgui_bundle import imgui

from ui.tools.base import BaseTool
from creation_lib.ui.widgets import pick_folder
from creation_lib.ui.widgets.forms import begin_form, end_form, draw_path_row

_log = logging.getLogger("tools.modlist_merger")


class MO2Merger:
    """Merges modlist.txt, loadorder.txt, and archives.txt from two MO2 profiles."""

    @staticmethod
    def _normalize(line: str) -> str:
        line = line.strip()
        if line and line[0] in ("+", "-"):
            return line[1:].strip()
        return line

    @staticmethod
    def _get_state(line: str) -> str:
        line = line.strip()
        if line and line[0] in ("+", "-"):
            return line[0]
        return "-"

    @staticmethod
    def _is_separator(line: str) -> bool:
        return MO2Merger._normalize(line).lower().endswith("_separator")

    def parse_modlist(self, filepath: str) -> dict:
        if not os.path.exists(filepath):
            return {"_order": [], "_orphans": []}

        structure: dict = {"_order": [], "_orphans": []}
        current_sep = None

        with open(filepath, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if self._is_separator(line):
                    sep_name = self._normalize(line).lower()
                    current_sep = sep_name
                    if sep_name not in structure:
                        structure[sep_name] = {"state": self._get_state(line), "mods": []}
                        structure["_order"].append(sep_name)
                else:
                    if current_sep:
                        structure[current_sep]["mods"].append(line)
                    else:
                        structure["_orphans"].append(line)

        return structure

    def merge_modlists(self, master_file: str, secondary_file: str, output_file: str) -> str:
        master = self.parse_modlist(master_file)
        secondary = self.parse_modlist(secondary_file)

        existing = set()
        for sep_name in master.get("_order", []):
            for mod in master[sep_name]["mods"]:
                existing.add(self._normalize(mod).lower())
        for mod in master.get("_orphans", []):
            existing.add(self._normalize(mod).lower())

        added_count = 0
        for sep_name in secondary.get("_order", []):
            sep_data = secondary[sep_name]
            new_mods = []
            for mod in sep_data["mods"]:
                key = self._normalize(mod).lower()
                if key not in existing:
                    new_mods.append(mod)
                    existing.add(key)
            if new_mods:
                if sep_name in master:
                    master[sep_name]["mods"].extend(new_mods)
                else:
                    master[sep_name] = {"state": sep_data["state"], "mods": new_mods}
                    master["_order"].append(sep_name)
                added_count += len(new_mods)

        for mod in secondary.get("_orphans", []):
            key = self._normalize(mod).lower()
            if key not in existing:
                master["_orphans"].append(mod)
                existing.add(key)
                added_count += 1

        # Ensure Base separator is last
        order = master.get("_order", [])
        if "base_separator" in order:
            master["_order"] = [k for k in order if k != "base_separator"] + ["base_separator"]

        with open(output_file, "w", encoding="utf-8") as f:
            f.write("# This file was automatically generated by Mod Organizer.\n")
            for mod in master.get("_orphans", []):
                f.write(f"{mod}\n")
            for sep_name in master.get("_order", []):
                sep_data = master[sep_name]
                f.write(f"{sep_data['state']}{sep_name}\n")
                for mod in sep_data["mods"]:
                    f.write(f"{mod}\n")

        return f"Merged modlist: {added_count} new entries added"

    def merge_simple_list(self, master_file: str, secondary_file: str, output_file: str, file_type: str) -> str:
        master_items: set[str] = set()
        result: list[str] = []

        if os.path.exists(master_file):
            with open(master_file, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#"):
                        master_items.add(line.lower())
                        result.append(line)

        added = 0
        if os.path.exists(secondary_file):
            with open(secondary_file, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#"):
                        if line.lower() not in master_items:
                            result.append(line)
                            master_items.add(line.lower())
                            added += 1

        with open(output_file, "w", encoding="utf-8") as f:
            if file_type == "loadorder":
                f.write("# This file was automatically generated by Mod Organizer.\n")
            for item in result:
                f.write(f"{item}\n")

        return f"Merged {file_type}: {added} new items"

    def merge_profiles(self, master_dir: str, secondary_dir: str, output_dir: str) -> list[str]:
        master = Path(master_dir)
        secondary = Path(secondary_dir)
        output = Path(output_dir)
        output.mkdir(parents=True, exist_ok=True)

        results = []
        results.append(self.merge_modlists(
            str(master / "modlist.txt"),
            str(secondary / "modlist.txt"),
            str(output / "modlist.txt"),
        ))
        results.append(self.merge_simple_list(
            str(master / "loadorder.txt"),
            str(secondary / "loadorder.txt"),
            str(output / "loadorder.txt"),
            "loadorder",
        ))
        results.append(self.merge_simple_list(
            str(master / "archives.txt"),
            str(secondary / "archives.txt"),
            str(output / "archives.txt"),
            "archives",
        ))
        return results


class ModlistMergerTool(BaseTool):
    name = "Modlist Merger"
    tool_id = "modlist_merger"
    description = "Merge two MO2 profiles"
    category = "Mod Tools"

    def __init__(self):
        super().__init__()
        self._master_dir = ""
        self._secondary_dir = ""
        self._output_dir = ""

    def draw_content(self) -> None:
        if begin_form("##modlist_merger"):
            _, clicked = draw_path_row("Master", self._master_dir)
            if clicked:
                path = pick_folder("Select master profile folder")
                if path:
                    self._master_dir = path

            _, clicked = draw_path_row("Secondary", self._secondary_dir)
            if clicked:
                path = pick_folder("Select secondary profile folder")
                if path:
                    self._secondary_dir = path

            _, clicked = draw_path_row("Output", self._output_dir)
            if clicked:
                path = pick_folder("Select output folder")
                if path:
                    self._output_dir = path
            end_form()

        imgui.spacing()
        imgui.separator()
        imgui.spacing()

        if imgui.button("Merge Profiles", imgui.ImVec2(160, 0)):
            if not self._master_dir or not os.path.isdir(self._master_dir):
                self._error_msg = "Please select a valid master profile folder."
                return
            if not self._secondary_dir or not os.path.isdir(self._secondary_dir):
                self._error_msg = "Please select a valid secondary profile folder."
                return
            if not self._output_dir:
                self._error_msg = "Please select an output folder."
                return

            try:
                os.makedirs(self._output_dir, exist_ok=True)
                merger = MO2Merger()
                results = merger.merge_profiles(self._master_dir, self._secondary_dir, self._output_dir)
                self._result_msg = "\n".join(results)
            except Exception as e:
                self._error_msg = f"Merge failed: {e}"
